xfyun.lo: /home/jiafd/workspace/phpxfyun/xfyun.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/jiafd/workspace/phpxfyun $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/jiafd/workspace/phpxfyun/xfyun.c -o xfyun.lo 
$(phplibdir)/xfyun.la: ./xfyun.la
	$(LIBTOOL) --mode=install cp ./xfyun.la $(phplibdir)

./xfyun.la: $(shared_objects_xfyun) $(XFYUN_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_xfyun) $(XFYUN_SHARED_LIBADD)

